### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by Oodaloop80** [PaloAltoNetworks/redist-check#1]
## Describe the bug
When executing the requirements script and SSL Error is returned about a self signed certificate

## Expected behavior

Installation of the required files should take place when executing the requirements script.
`pip3 install -r requirements.txt`

## Current behavior

When running the requirement script.
`pip3 install -r requirements.txt`

The following error is returned.
`WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1007)'))': /simple/requests/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1007)'))': /simple/requests/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1007)'))': /simple/requests/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1007)'))': /simple/requests/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1007)'))': /simple/requests/
Could not fetch URL https://pypi.org/simple/requests/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/requests/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1007)'))) - skipping
ERROR: Could not find a version that satisfies the requirement Requests==2.31.0 (from versions: none)
ERROR: No matching distribution found for Requests==2.31.0
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1007)'))) - skipping`
## Steps to reproduce

1. Included txt file of IPs in same folder as code
2. In powershell, navigated to same folder where code is located
3. Ran the `pip3 install -r requirements.txt`
4. Received error

## Screenshots

![CaptureGITHUB](https://github.com/PaloAltoNetworks/redist-check/assets/152920627/5ceefe75-1e9f-4547-b8a0-b8094fb7dd5d)

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): Python 3.10 64bit
- Operating System and version (desktop or mobile): Windows 11 64bit
- Link to your project:

**Comment by rlemm-pan** [comment]
Installing these modules using pip is a prerequisite before running the script.  

Check out this article.  It might help your issue:

[](https://stackoverflow.com/questions/25981703/pip-install-fails-with-connection-error-ssl-certificate-verify-failed-certi)

**Comment by element0355** [comment]
I also had the same issue you can add a trusted host to the command line.

pip install -trusted-host pypi.org -trusted-host files.pythonhosted.org -r requirements.txt

**Comment by Oodaloop80** [comment]
> I also had the same issue you can add a trusted host to the command line.
> 
> pip install -trusted-host pypi.org -trusted-host files.pythonhosted.org -r requirements.txt

Actually, I take back my previous comment. It need -- instead of - and it worked. Thank you!
