### ISSUE TITLE
splitlines call

### ISSUE THREAD

**Issue by Doemaas** [PaloAltoNetworks/redist-check#3]
python 3.9.18, macOS 13.6.2

Error:
Traceback (most recent call last):
  File "redist-check/redist-check.py", line 773, in <module>
    devices, username, password, filename = get_devices()
  File "redist-check/redist-check.py", line 137, in get_devices
    while("" in devices):
TypeError: argument of type 'builtin_function_or_method' is not iterable

For me line 135 adding "()" to splitlines made it work. Otherwise devices is not an iterable list but a function.
135: devices = df.read().splitlines()

**Comment by rlemm-pan** [comment]
Fixed.  Thank you!!!
